### ISSUE TITLE
[Back? end] Feed (Home.js) page left side columns

### ISSUE THREAD

**Issue by dionkb** [Sabplpz/Concert-Connect#114]
Upcoming concerts needs to be sorted by the date, showing the closest ones first
Favorite artists and venues don't really do anything since we don't have a clean way of adding (liking) either of them at the moment
Favorite genre will either need to be added to the user model, or we use the users saved concerts/artists to create a list of most frequent genre and populate it that way

**Comment by Sabplpz** [comment]
For Genre, using the concert/artists might be the bets way

**Comment by Sabplpz** [comment]
Concerts now sort by date! :)

**Comment by dionkb** [comment]
Concerts dont show up at all now :'(

**Comment by dionkb** [comment]
All hail bobby!
