### ISSUE TITLE
[Front end] Artist Spotify button

### ISSUE THREAD

**Issue by Sabplpz** [Sabplpz/Concert-Connect#147]
In concert.js, if you clcik on the artist name, it takes you to their spotify, however that is not obvious. I suggest we make the name look like a green button or have the spotify link to the side of the artist

**Comment by Sabplpz** [comment]
Where does the button take you?
Can you provide an example?

**Comment by dionkb** [comment]
Also it looks like sometimes it fills the Artist name in, and sometimes it fills the concert name instead? And not all of the one that show up actually link anywhere
