### ISSUE TITLE
[Front end] Profile pagination and dynamic follow button

### ISSUE THREAD

**Issue by miamreid** [Sabplpz/Concert-Connect#91]
If looking at your own profile, do not show follow button. 

If looking at someone else's profile that you follow, button should be "unfollow" with a different color. 

If looking at someone else's profile that you don't follow, leave follow button

**Comment by dionkb** [comment]
For point 2: Follow button becomes unfollow button now. Still some issues:
- I didn't add color changing
- It doesn't automatically change, you must refresh page
