### ISSUE TITLE
[back end] user profile picture save to database

### ISSUE THREAD

**Issue by miamreid** [Sabplpz/Concert-Connect#93]
when user selects a profile picture, save to their user model

**Comment by Sabplpz** [comment]
Done! Just as an explanation, the picture itself is not being saved, as that would have required a lot more. What's being saved is the name of the avatar, and once the user is created or they log in, the avatar utils function handleAvatar will compare the short name to a set name and return the image that is available within the src folder. This is a much easier solution, in my opinion.
