### ISSUE TITLE
[Back end/front end] Connect database seeds or live database to front end display

### ISSUE THREAD

**Issue by miamreid** [Sabplpz/Concert-Connect#94]
- User top artists
- User top genres
- User top venues
- Username on feed posts, comments, and profile page
- followers 
- profile picture

**Comment by dionkb** [comment]
I added username on feed posts, and profile page where I could
Sabrina added the avatar as the profile picture

Still need:
- User top artists (Bobby is working on these)
- User top genres (Bobby is working on these)
- User top venues (Bobby is working on these)
- followers (need to add ability to follow another user

**Comment by dionkb** [comment]
Users can now click on a "follow" button on a user profile and they are properly added to that users "follow" array. Still need to add validation only allow a single follow, and not following yourself (both are already separate issues)

- User top artists (Bobby is working on these)
- User top genres (Bobby is working on these)
- User top venues (Bobby is working on these)
